/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.merlin;

import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucky
 */
public class LogInPanel extends javax.swing.JPanel {

    /**
     * @return the initial
     */
    public String getInitial() {
        return initial;
    }

    /**
     * @param initial the initial to set
     */
    public void setInitial(String initial) {
        this.initial = initial;
    }

    private final String driver;
    private final String f_user;
    private final String f_pass;
    private String initial;
    private DateHelper dateHelp;
    private Calendar currentDate;
    private String curDateText;
    Config con = new Config();
    



    
    /**
     * Creates new form LogInPanel
     */
    public LogInPanel() {
        this.driver = "jdbc:mariadb://" + this.con.getProp("IP") + ":" + this.con.getProp("port") + "/merlininventorydatabase";
     this.f_user = this.con.getProp("username");
     this.f_pass = this.con.getProp("password");
     
     this.initial = "";
     this.dateHelp = new DateHelper();
     this.currentDate = Calendar.getInstance();
     this.curDateText = this.dateHelp.formatDate(this.currentDate.getTime());
     initComponents();
     this.tempUsername.requestFocusInWindow(); } public void requestFocusOnUsername() {
     this.tempUsername.requestFocusInWindow();
    }
     
     public void erasePW() {
         this.tempPassword.setText("");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tempUsername = new javax.swing.JTextField();
        tempPassword = new javax.swing.JPasswordField();
        exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SignIn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 625));
        setMinimumSize(new java.awt.Dimension(1000, 625));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(80, 80, 80));
        jLabel4.setText("Password:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tempUsername.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        tempUsername.setForeground(new java.awt.Color(51, 51, 51));
        tempUsername.setText("admin");
        tempUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tempUsername.setMargin(new java.awt.Insets(2, 15, 2, 15));
        tempUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempUsernameActionPerformed(evt);
            }
        });
        tempUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempUsernameKeyPressed(evt);
            }
        });

        tempPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        tempPassword.setForeground(new java.awt.Color(51, 51, 51));
        tempPassword.setText("admin123");
        tempPassword.setMargin(new java.awt.Insets(2, 15, 2, 15));
        tempPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempPasswordKeyPressed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        exit.setForeground(new java.awt.Color(79, 119, 141));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(80, 80, 80));
        jLabel3.setText("Username:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        SignIn.setBackground(new java.awt.Color(79, 119, 141));
        SignIn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        SignIn.setForeground(new java.awt.Color(255, 255, 255));
        SignIn.setText("Sign In");
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tempPassword)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tempUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                .addContainerGap(409, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tempPassword, tempUsername});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(tempPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SignIn, exit});

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 270, 630, 252));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/merlin logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 640, 252));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 119, 141));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to Merlin Pawn Management System!");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 239, 1280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tempUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempUsernameKeyPressed
        int key =evt.getKeyCode();
        if (key == 10){
            tempPassword.requestFocusInWindow();
            tempPassword.selectAll();
        }
        if (key == 27) {
            System.exit(0);
        }
    }//GEN-LAST:event_tempUsernameKeyPressed

    private void tempPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempPasswordKeyPressed
        int key =evt.getKeyCode();
        if (key == 10){
            tempPassword.requestFocusInWindow();
            tempPassword.selectAll();
        }
        if (key == 27) {
            System.exit(0);
        }
        if (key == KeyEvent.VK_ENTER) {
            SignInActionPerformed(null);
        }
    }//GEN-LAST:event_tempPasswordKeyPressed

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
        String use = "";
        String pass = "";
        String name = "";
        String ini = "";
        int level = 3;
        boolean acceptSignIn = false;
  
        try {
            Connection connect = DriverManager.getConnection(this.driver, this.f_user, this.f_pass);
            Statement query = connect.createStatement();
            ResultSet rs = query.executeQuery("Select username, password, first_name, last_name, initials, user_level from merlininventorydatabase.use_pass");  
            while (rs.next()) {
                use = rs.getString("username");
                pass = rs.getString("password");
                name = rs.getString("first_name").concat(" " + rs.getString("last_name"));
                ini = rs.getString("initials");
                level = rs.getInt("user_level");
                if (this.tempUsername.getText().equals(use) && this.tempPassword.getText().equals(pass)) {
                    acceptSignIn = true;
                break;
                } 
                acceptSignIn = false;
                } 
 
        if (acceptSignIn) {
            this.con.saveProp("last_user", use);
            this.con.saveProp("last_username", name);
            this.con.saveProp("last_login", this.dateHelp.getDateTime());
            this.con.saveProp("last_ini_used", ini);
            this.con.saveProp("user_level", String.valueOf(level));
            int rowcount = 0;
            try {
                ResultSet rs2 = query.executeQuery("Select COUNT(*) from cashtransactions.running_balance");
                while (rs2.next()) {
                rowcount = rs2.getInt(1);
            }
            rs2.close();
            } catch (SQLException ex) {
                this.con.saveProp("mpis_last_error", String.valueOf(ex));
                Logger.getLogger(LogInPanel.class.getName()).log(Level.SEVERE, (String)null, ex);
            } 
            if (rowcount == 0) {
                BeginningBalance beginBal = new BeginningBalance(null, true);
                beginBal.setVisible(true);
            } else {
                ResultSet rs2 = query.executeQuery("Select date, ending_balance from cashtransactions.running_balance");
                double next_begin_bal = 0.0D;
/* 266 */           String latestDate = "";
/* 267 */           while (rs2.next()) {
/* 268 */             latestDate = rs2.getString(1);
/* 269 */             next_begin_bal = rs2.getDouble(2);
/*     */           } 
/*     */ 
/*     */ 
/*     */           
/* 274 */           this.currentDate.set(11, 0);
/* 275 */           this.currentDate.set(12, 0);
/* 276 */           this.currentDate.set(13, 0);
/* 277 */           this.currentDate.set(14, 0);
/* 278 */           if (this.currentDate.getTime().after(this.dateHelp.formatStringToDate(latestDate))) {
/*     */             
/* 280 */             File file = new File("C:\\MPIS\\daytranx");
/* 281 */             File[] contents = file.listFiles();
/* 282 */             if (contents != null) {
/* 283 */               for (File f : contents) {
/* 284 */                 System.out.println("deleting files");
/* 285 */                 f.delete();
/*     */               } 
/*     */             }
/* 288 */             File file2 = new File("C:\\MPIS\\tempRep");
/* 289 */             File[] contents2 = file2.listFiles();
/* 290 */             if (contents2 != null) {
/* 291 */               for (File f2 : contents2) {
/* 292 */                 System.out.println("deleting files onf files 2");
/* 293 */                 f2.delete();
/*     */               } 
/*     */             }
/*     */             
/* 297 */             File file3 = new File("C:\\MPIS\\tempRep\\transfers");
/* 298 */             File[] contents3 = file3.listFiles();
/* 299 */             if (contents3 != null) {
/* 300 */               for (File f3 : contents3) {
/* 301 */                 System.out.println("deleting files on files 3");
/* 302 */                 f3.delete();
/*     */               } 
/*     */             }
/*     */ 
/*     */             
/* 307 */             File file4 = new File("C:\\MPIS\\tempRep\\pettycash");
/*     */ 
/*     */ 
/*     */             
/* 311 */             File[] contents4 = file4.listFiles();
/* 312 */             if (contents4 != null)
/* 313 */               for (File f4 : contents4) {
/* 314 */                 System.out.println("deleting files onf files 4");
/* 315 */                 if (f4.delete()) System.out.println("files 4 deleted successfully");
/*     */               
/*     */               }  
/* 318 */             query.executeUpdate("Insert into cashtransactions.running_balance (date, beginning_balance, ending_balance, total_cash_inflow, total_cash_outflow) values ('" + this.curDateText + "', " + String.valueOf(next_begin_bal) + ", " + String.valueOf(next_begin_bal) + ", " + 0.0D + ", " + 0.0D + ")");
/*     */           } 
/*     */         } 
/*     */         
/* 322 */         setVisible(false);
/*     */       } else {
/*     */         
/* 325 */         JOptionPane.showMessageDialog(null, "Username/Password Invalid! \nPlease retry.", "Error", 0);
/* 326 */         this.tempPassword.requestFocusInWindow();
/* 327 */         this.tempPassword.selectAll();
/*     */       }
/*     */     
/* 330 */     } catch (SQLException ex) {
/* 331 */       this.con.saveProp("mpis_last_error", String.valueOf(ex));
/* 332 */       System.out.println(ex);
/* 333 */       System.out.println("sql error on sign in");
/*     */     } 
    }//GEN-LAST:event_SignInActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.con.saveProp("last_logout", this.dateHelp.getDateTime());
/* 339 */     Management manage = new Management();
/* 340 */     DateHelper dateHelp = new DateHelper();
/* 341 */     File tempFolder = new File("D:\\MPIS_BackUp");
/* 342 */     if (!tempFolder.exists()) {
/* 343 */       tempFolder.mkdir();
/*     */     }
/*     */     
///* 346 */     if (manage.backupDB("merlininventorydatabase", "root", "merlin", "D:\\MPIS_BackUp\\" + dateHelp.getSavingDate() + " " + dateHelp.getSavingTime()) == true)
/* 347 */       System.out.println("backup successful"); 
/* 348 */     System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        this.tempUsername.setText(this.con.getProp("last_user"));
        requestFocusOnUsername();
    }//GEN-LAST:event_formComponentShown

    private void tempUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignIn;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField tempPassword;
    private javax.swing.JTextField tempUsername;
    // End of variables declaration//GEN-END:variables
}
