/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.merlin;

/**
 *
 * @author Lucky
 */
public class ViewNewAddedItem extends javax.swing.JDialog { 

    /**
     * Creates new form ViewMode
     */
    public ViewNewAddedItem(java.awt.Frame parent, boolean modal, Sangla newLoan) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
/*  29 */     this.noButton.requestFocusInWindow();
/*  30 */     DecimalHelper decHelp = new DecimalHelper();
/*     */     this.contactNo.setText(newLoan.getContact_no());
/*  34 */     this.papeletaNoVM.setText(newLoan.getPap_num());
/*  37 */     this.clientNameVM.setText(newLoan.getClient_name());
/*  38 */     this.clientAddressVM.setText(newLoan.getClient_address());
/*  39 */     this.itemDescVM.setText(newLoan.getItem_description());
/*  40 */     this.branchVM.setText(newLoan.getBranch());
/*  41 */     this.itemClassificationVM.setText(newLoan.getClassification());
/*  42 */     this.processedByVM.setText(newLoan.getProcessed_by());
/*  43 */     this.transactionDateVM.setText(newLoan.getTransaction_date());
/*  44 */     this.maturityDateVM.setText(newLoan.getMaturity_date());
/*  45 */     this.expiryDateVM.setText(newLoan.getExpiration_date());
/*  46 */     this.principalVM.setText(decHelp.FormatNumber(newLoan.getPrincipal()));
/*  47 */     this.interestVM.setText(decHelp.FormatPercent(newLoan.getAdvance_interest()));
/*  48 */     this.insurancetVM.setText(decHelp.FormatNumber(newLoan.getInsurance()));
/*  49 */     this.serviceChargeVM.setText(decHelp.FormatNumber(newLoan.getService_charge()));
/*  50 */     this.otherChargesVM.setText(decHelp.FormatNumber(newLoan.getOther_charges()));
/*  51 */     this.netProceedsVM.setText(decHelp.FormatNumber(newLoan.getNet_proceeds()));
/*  52 */     this.statusVM.setText(newLoan.getStatus());
/*  53 */     this.remarksVM.setText(newLoan.getRemarks());
/*     */     
/*  51 */     this.noButton.requestFocusInWindow();
    }
    
    private boolean allow = false;
    
    public boolean allowAddToDatabase() {
/*  55 */     return this.allow;
/*     */   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        papeletaNoVM = new javax.swing.JTextField();
        clientNameVM = new javax.swing.JTextField();
        statusVM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientAddressVM = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemDescVM = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        remarksVM = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        branchVM = new javax.swing.JTextField();
        itemClassificationVM = new javax.swing.JTextField();
        processedByVM = new javax.swing.JTextField();
        transactionDateVM = new javax.swing.JTextField();
        maturityDateVM = new javax.swing.JTextField();
        expiryDateVM = new javax.swing.JTextField();
        principalVM = new javax.swing.JTextField();
        interestVM = new javax.swing.JTextField();
        insurancetVM = new javax.swing.JTextField();
        serviceChargeVM = new javax.swing.JTextField();
        otherChargesVM = new javax.swing.JTextField();
        netProceedsVM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        contactNo = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(239, 246, 250));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 119, 141), 3, true));

        yesButton.setBackground(new java.awt.Color(79, 119, 141));
        yesButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        yesButton.setForeground(new java.awt.Color(255, 255, 255));
        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        noButton.setForeground(new java.awt.Color(79, 119, 141));
        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });
        noButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noButtonKeyPressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(79, 119, 141));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Please confirm that all items above are TRUE and CORRECT.");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(79, 119, 141));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Are you sure you want to add this item?");

        jPanel1.setBackground(new java.awt.Color(239, 246, 250));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Loan No.");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Client Name");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Client Address");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Status");

        papeletaNoVM.setEditable(false);
        papeletaNoVM.setBackground(new java.awt.Color(255, 255, 255));
        papeletaNoVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        papeletaNoVM.setForeground(new java.awt.Color(51, 51, 51));

        clientNameVM.setEditable(false);
        clientNameVM.setBackground(new java.awt.Color(255, 255, 255));
        clientNameVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        clientNameVM.setForeground(new java.awt.Color(51, 51, 51));

        statusVM.setEditable(false);
        statusVM.setBackground(new java.awt.Color(255, 255, 255));
        statusVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        statusVM.setForeground(new java.awt.Color(51, 51, 51));

        clientAddressVM.setEditable(false);
        clientAddressVM.setBackground(new java.awt.Color(255, 255, 255));
        clientAddressVM.setColumns(20);
        clientAddressVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        clientAddressVM.setForeground(new java.awt.Color(51, 51, 51));
        clientAddressVM.setLineWrap(true);
        clientAddressVM.setRows(2);
        jScrollPane1.setViewportView(clientAddressVM);

        itemDescVM.setEditable(false);
        itemDescVM.setBackground(new java.awt.Color(255, 255, 255));
        itemDescVM.setColumns(20);
        itemDescVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        itemDescVM.setForeground(new java.awt.Color(51, 51, 51));
        itemDescVM.setLineWrap(true);
        itemDescVM.setRows(3);
        itemDescVM.setWrapStyleWord(true);
        jScrollPane2.setViewportView(itemDescVM);

        remarksVM.setEditable(false);
        remarksVM.setBackground(new java.awt.Color(255, 255, 255));
        remarksVM.setColumns(20);
        remarksVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        remarksVM.setForeground(new java.awt.Color(51, 51, 51));
        remarksVM.setLineWrap(true);
        remarksVM.setRows(2);
        remarksVM.setWrapStyleWord(true);
        jScrollPane3.setViewportView(remarksVM);

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Branch");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Classification");

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Processed By");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Transaction Date");

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Maturity Date");

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Expiry Date");

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Principal");

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Advance Interest");

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Insurance");

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Service Charge");

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Other Charges");

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Net Proceeds");

        branchVM.setEditable(false);
        branchVM.setBackground(new java.awt.Color(255, 255, 255));
        branchVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        branchVM.setForeground(new java.awt.Color(51, 51, 51));

        itemClassificationVM.setEditable(false);
        itemClassificationVM.setBackground(new java.awt.Color(255, 255, 255));
        itemClassificationVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        itemClassificationVM.setForeground(new java.awt.Color(51, 51, 51));

        processedByVM.setEditable(false);
        processedByVM.setBackground(new java.awt.Color(255, 255, 255));
        processedByVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        processedByVM.setForeground(new java.awt.Color(51, 51, 51));

        transactionDateVM.setEditable(false);
        transactionDateVM.setBackground(new java.awt.Color(255, 255, 255));
        transactionDateVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        transactionDateVM.setForeground(new java.awt.Color(51, 51, 51));

        maturityDateVM.setEditable(false);
        maturityDateVM.setBackground(new java.awt.Color(255, 255, 255));
        maturityDateVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        maturityDateVM.setForeground(new java.awt.Color(51, 51, 51));

        expiryDateVM.setEditable(false);
        expiryDateVM.setBackground(new java.awt.Color(255, 255, 255));
        expiryDateVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        expiryDateVM.setForeground(new java.awt.Color(51, 51, 51));

        principalVM.setEditable(false);
        principalVM.setBackground(new java.awt.Color(255, 255, 255));
        principalVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        principalVM.setForeground(new java.awt.Color(51, 51, 51));

        interestVM.setEditable(false);
        interestVM.setBackground(new java.awt.Color(255, 255, 255));
        interestVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        interestVM.setForeground(new java.awt.Color(51, 51, 51));

        insurancetVM.setEditable(false);
        insurancetVM.setBackground(new java.awt.Color(255, 255, 255));
        insurancetVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        insurancetVM.setForeground(new java.awt.Color(51, 51, 51));

        serviceChargeVM.setEditable(false);
        serviceChargeVM.setBackground(new java.awt.Color(255, 255, 255));
        serviceChargeVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        serviceChargeVM.setForeground(new java.awt.Color(51, 51, 51));

        otherChargesVM.setEditable(false);
        otherChargesVM.setBackground(new java.awt.Color(255, 255, 255));
        otherChargesVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        otherChargesVM.setForeground(new java.awt.Color(51, 51, 51));

        netProceedsVM.setEditable(false);
        netProceedsVM.setBackground(new java.awt.Color(255, 255, 255));
        netProceedsVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        netProceedsVM.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Item Description");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Remarks");

        contactNo.setEditable(false);
        contactNo.setBackground(new java.awt.Color(255, 255, 255));
        contactNo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        contactNo.setForeground(new java.awt.Color(51, 51, 51));

        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setText("Contact No.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(serviceChargeVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(transactionDateVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                                .addComponent(principalVM, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(otherChargesVM, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(interestVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                                        .addComponent(maturityDateVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(8, 8, 8)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(clientNameVM, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(papeletaNoVM, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(statusVM, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jLabel6))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(branchVM, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(itemClassificationVM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(processedByVM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(expiryDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(insurancetVM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(netProceedsVM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {branchVM, contactNo, expiryDateVM, insurancetVM, interestVM, itemClassificationVM, maturityDateVM, netProceedsVM, otherChargesVM, papeletaNoVM, principalVM, processedByVM, serviceChargeVM, statusVM, transactionDateVM});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(papeletaNoVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(clientNameVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(1, 1, 1)
                        .addComponent(contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemClassificationVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel11))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processedByVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maturityDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(principalVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insurancetVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceChargeVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherChargesVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netProceedsVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Merlin Pawnshop, Inc.   All Rights Reserved. © 2011");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noButton)
                    .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {noButton, yesButton});

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        this.allow = true;
/* 482 */     setVisible(false);
/* 483 */     dispose();
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        this.allow = false;
/* 489 */     setVisible(false);
/* 490 */     dispose();
    }//GEN-LAST:event_noButtonActionPerformed

    private void noButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noButtonKeyPressed
        int key = evt.getKeyCode();
/* 496 */     if (key == 37 || key == 9) {
/* 497 */       this.yesButton.requestFocusInWindow();
/*     */     }
    }//GEN-LAST:event_noButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNewAddedItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNewAddedItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNewAddedItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNewAddedItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() { private Sangla newLoan;
            public void run() {
                ViewNewAddedItem dialog = new ViewNewAddedItem(new javax.swing.JFrame(), true, this.newLoan);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branchVM;
    private javax.swing.JTextArea clientAddressVM;
    private javax.swing.JTextField clientNameVM;
    private javax.swing.JTextField contactNo;
    private javax.swing.JTextField expiryDateVM;
    private javax.swing.JTextField insurancetVM;
    private javax.swing.JTextField interestVM;
    private javax.swing.JTextField itemClassificationVM;
    private javax.swing.JTextArea itemDescVM;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maturityDateVM;
    private javax.swing.JTextField netProceedsVM;
    private javax.swing.JButton noButton;
    private javax.swing.JTextField otherChargesVM;
    private javax.swing.JTextField papeletaNoVM;
    private javax.swing.JTextField principalVM;
    private javax.swing.JTextField processedByVM;
    private javax.swing.JTextArea remarksVM;
    private javax.swing.JTextField serviceChargeVM;
    private javax.swing.JTextField statusVM;
    private javax.swing.JTextField transactionDateVM;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
