/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpis_mariadb_2;

/**
 *
 * @author Lucky
 */
public class LeftContainer extends javax.swing.JPanel {

    /**
     * Creates new form LeftContainer
     */
    public LeftContainer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new mpis_mariadb_2.Menu();
        newPledge1 = new mpis_mariadb_2.NewPledge();
        renewal1 = new mpis_mariadb_2.Renewal();
        redemption1 = new mpis_mariadb_2.Redemption();
        search1 = new mpis_mariadb_2.Search();
        expired1 = new mpis_mariadb_2.Expired();
        vaultInvPanel1 = new mpis_mariadb_2.VaultInvPanel();
        repossessedPanel1 = new mpis_mariadb_2.RepossessedPanel();
        statistics1 = new mpis_mariadb_2.Statistics();
        management1 = new mpis_mariadb_2.Management();
        empenoRescate1 = new mpis_mariadb_2.EmpenoRescate();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(765, 623));
        setMinimumSize(new java.awt.Dimension(765, 623));
        setPreferredSize(new java.awt.Dimension(765, 623));
        setLayout(new java.awt.CardLayout());
        add(menu1, "card2");
        add(newPledge1, "card3");
        add(renewal1, "card4");
        add(redemption1, "card5");
        add(search1, "card6");
        add(expired1, "card7");
        add(vaultInvPanel1, "card8");
        add(repossessedPanel1, "card9");
        add(statistics1, "card10");
        add(management1, "card11");
        add(empenoRescate1, "card12");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mpis_mariadb_2.EmpenoRescate empenoRescate1;
    private mpis_mariadb_2.Expired expired1;
    private mpis_mariadb_2.Management management1;
    private mpis_mariadb_2.Menu menu1;
    private mpis_mariadb_2.NewPledge newPledge1;
    private mpis_mariadb_2.Redemption redemption1;
    private mpis_mariadb_2.Renewal renewal1;
    private mpis_mariadb_2.RepossessedPanel repossessedPanel1;
    private mpis_mariadb_2.Search search1;
    private mpis_mariadb_2.Statistics statistics1;
    private mpis_mariadb_2.VaultInvPanel vaultInvPanel1;
    // End of variables declaration//GEN-END:variables
}
