/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpis_mariadb_2;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Lucky
 */
public class Menu extends javax.swing.JPanel {

    /**
     * @return the menuSelect
     */
    public int getMenuSelect() {
        return menuSelect;
    }

    /**
     * @param menuSelect the menuSelect to set
     */
    public void setMenuSelect(int menuSelect) {
        this.menuSelect = menuSelect;
    }

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    private int menuSelect;
    
    public void requestFocusOnButtons() {
        this.newPledgeLoanMenuBtn.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logInPanel1 = new mpis_mariadb_2.LogInPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 37), new java.awt.Dimension(0, 37), new java.awt.Dimension(32767, 37));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 37), new java.awt.Dimension(0, 37), new java.awt.Dimension(32767, 37));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        jPanel1 = new javax.swing.JPanel();
        newPledgeLoanMenuBtn = new javax.swing.JButton();
        loanRenewalMenuBtn = new javax.swing.JButton();
        redeemLoanMenuBtn = new javax.swing.JButton();
        searchMenuBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        expiredMenuBtn = new javax.swing.JButton();
        vaultInvMenuBtn = new javax.swing.JButton();
        repossessedMenuBtn = new javax.swing.JButton();
        statisticsMenuBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        empenoRescateMenuBtn = new javax.swing.JButton();
        setttingsMenuBtn = new javax.swing.JButton();
        helpMenuBtn = new javax.swing.JButton();
        logOutMenuBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(765, 623));
        setMinimumSize(new java.awt.Dimension(765, 623));
        setPreferredSize(new java.awt.Dimension(765, 623));
        setLayout(new java.awt.BorderLayout());
        add(filler2, java.awt.BorderLayout.NORTH);
        add(filler3, java.awt.BorderLayout.SOUTH);
        add(filler4, java.awt.BorderLayout.EAST);
        add(filler5, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.GridLayout(6, 4));

        newPledgeLoanMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/diamond.png"))); // NOI18N
        newPledgeLoanMenuBtn.setBorder(null);
        newPledgeLoanMenuBtn.setBorderPainted(false);
        newPledgeLoanMenuBtn.setContentAreaFilled(false);
        newPledgeLoanMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPledgeLoanMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(newPledgeLoanMenuBtn);

        loanRenewalMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/renew.png"))); // NOI18N
        loanRenewalMenuBtn.setBorder(null);
        loanRenewalMenuBtn.setBorderPainted(false);
        loanRenewalMenuBtn.setContentAreaFilled(false);
        loanRenewalMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanRenewalMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loanRenewalMenuBtn);

        redeemLoanMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/clipboard.png"))); // NOI18N
        redeemLoanMenuBtn.setBorder(null);
        redeemLoanMenuBtn.setBorderPainted(false);
        redeemLoanMenuBtn.setContentAreaFilled(false);
        redeemLoanMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redeemLoanMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(redeemLoanMenuBtn);

        searchMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/search.png"))); // NOI18N
        searchMenuBtn.setBorder(null);
        searchMenuBtn.setContentAreaFilled(false);
        searchMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchMenuBtn);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setLabelFor(newPledgeLoanMenuBtn);
        jLabel5.setText("NEW PLEDGE LOAN");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setLabelFor(loanRenewalMenuBtn);
        jLabel6.setText("LOAN RENEWAL");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setLabelFor(redeemLoanMenuBtn);
        jLabel7.setText("REDEEM LOAN");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setLabelFor(searchMenuBtn);
        jLabel8.setText("CUSTOMER SEARCH");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel8);

        expiredMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/time.png"))); // NOI18N
        expiredMenuBtn.setBorder(null);
        expiredMenuBtn.setBorderPainted(false);
        expiredMenuBtn.setContentAreaFilled(false);
        expiredMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiredMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(expiredMenuBtn);

        vaultInvMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/vault.png"))); // NOI18N
        vaultInvMenuBtn.setBorder(null);
        vaultInvMenuBtn.setBorderPainted(false);
        vaultInvMenuBtn.setContentAreaFilled(false);
        vaultInvMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaultInvMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(vaultInvMenuBtn);

        repossessedMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/repo.png"))); // NOI18N
        repossessedMenuBtn.setBorder(null);
        repossessedMenuBtn.setBorderPainted(false);
        repossessedMenuBtn.setContentAreaFilled(false);
        repossessedMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repossessedMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(repossessedMenuBtn);

        statisticsMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/line.png"))); // NOI18N
        statisticsMenuBtn.setBorder(null);
        statisticsMenuBtn.setBorderPainted(false);
        statisticsMenuBtn.setContentAreaFilled(false);
        statisticsMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(statisticsMenuBtn);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setLabelFor(expiredMenuBtn);
        jLabel13.setText("EXPIRED LOANS");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setLabelFor(vaultInvMenuBtn);
        jLabel14.setText("VAULT INVENTORY");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setLabelFor(repossessedMenuBtn);
        jLabel15.setText("REPOSSESSED/SOLD");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setLabelFor(statisticsMenuBtn);
        jLabel16.setText("STATISTICS");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel16);

        empenoRescateMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/books.png"))); // NOI18N
        empenoRescateMenuBtn.setBorder(null);
        empenoRescateMenuBtn.setBorderPainted(false);
        empenoRescateMenuBtn.setContentAreaFilled(false);
        empenoRescateMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empenoRescateMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(empenoRescateMenuBtn);

        setttingsMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/setting.png"))); // NOI18N
        setttingsMenuBtn.setBorder(null);
        setttingsMenuBtn.setBorderPainted(false);
        setttingsMenuBtn.setContentAreaFilled(false);
        setttingsMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setttingsMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(setttingsMenuBtn);

        helpMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/help.png"))); // NOI18N
        helpMenuBtn.setBorder(null);
        helpMenuBtn.setBorderPainted(false);
        helpMenuBtn.setContentAreaFilled(false);
        helpMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(helpMenuBtn);

        logOutMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mpis_mariadb_2/key.png"))); // NOI18N
        logOutMenuBtn.setBorder(null);
        logOutMenuBtn.setBorderPainted(false);
        logOutMenuBtn.setContentAreaFilled(false);
        logOutMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logOutMenuBtn);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setLabelFor(setttingsMenuBtn);
        jLabel21.setText("SETTINGS");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel21);

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setLabelFor(empenoRescateMenuBtn);
        jLabel22.setText("EMPENO/RESCATE");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel22);

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setLabelFor(helpMenuBtn);
        jLabel23.setText("HELP");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel23);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setLabelFor(logOutMenuBtn);
        jLabel24.setText("LOG OUT");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel24);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void newPledgeLoanMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPledgeLoanMenuBtnActionPerformed
        setMenuSelect(1);
        setVisible(false);
    }//GEN-LAST:event_newPledgeLoanMenuBtnActionPerformed

    private void loanRenewalMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanRenewalMenuBtnActionPerformed
        setMenuSelect(2);
        setVisible(false);
    }//GEN-LAST:event_loanRenewalMenuBtnActionPerformed

    private void redeemLoanMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redeemLoanMenuBtnActionPerformed
        setMenuSelect(3);
        setVisible(false);
    }//GEN-LAST:event_redeemLoanMenuBtnActionPerformed

    private void searchMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMenuBtnActionPerformed
        setMenuSelect(4);
        setVisible(false);
    }//GEN-LAST:event_searchMenuBtnActionPerformed

    private void expiredMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiredMenuBtnActionPerformed
        setMenuSelect(5);
        setVisible(false);
    }//GEN-LAST:event_expiredMenuBtnActionPerformed

    private void vaultInvMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaultInvMenuBtnActionPerformed
        setMenuSelect(6);
        setVisible(false);
    }//GEN-LAST:event_vaultInvMenuBtnActionPerformed

    private void repossessedMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repossessedMenuBtnActionPerformed
        setMenuSelect(7);
        setVisible(false);
    }//GEN-LAST:event_repossessedMenuBtnActionPerformed

    private void statisticsMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsMenuBtnActionPerformed
        setMenuSelect(8);
        setVisible(false);
    }//GEN-LAST:event_statisticsMenuBtnActionPerformed

    private void setttingsMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setttingsMenuBtnActionPerformed
        if (Integer.parseInt((new Config()).getProp("user_level")) == 3) {
            setMenuSelect(9);
            setVisible(false);
        }
    }//GEN-LAST:event_setttingsMenuBtnActionPerformed

    private void empenoRescateMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empenoRescateMenuBtnActionPerformed
        setMenuSelect(10);
        setVisible(false);
    }//GEN-LAST:event_empenoRescateMenuBtnActionPerformed

    private void helpMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuBtnActionPerformed
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(new File("C:\\MPIS\\help.docx"));
            }
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } 
    }//GEN-LAST:event_helpMenuBtnActionPerformed

    private void logOutMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuBtnActionPerformed
        setMenuSelect(99);
        setVisible(false);
    }//GEN-LAST:event_logOutMenuBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empenoRescateMenuBtn;
    private javax.swing.JButton expiredMenuBtn;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton helpMenuBtn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loanRenewalMenuBtn;
    private mpis_mariadb_2.LogInPanel logInPanel1;
    private javax.swing.JButton logOutMenuBtn;
    private javax.swing.JButton newPledgeLoanMenuBtn;
    private javax.swing.JButton redeemLoanMenuBtn;
    private javax.swing.JButton repossessedMenuBtn;
    private javax.swing.JButton searchMenuBtn;
    private javax.swing.JButton setttingsMenuBtn;
    private javax.swing.JButton statisticsMenuBtn;
    private javax.swing.JButton vaultInvMenuBtn;
    // End of variables declaration//GEN-END:variables
}
