/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpis_mariadb_2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


/**
 *
 * @author Lucky
 */
public class NewPledge extends javax.swing.JPanel {

    /**
     * Creates new form NewPledge
     */
    public NewPledge() {
        initComponents();
        clearFieldsInNewPledgeLoan();
    }
    
    private Config con = new Config();
    private final String driver = "jdbc:mariadb://" + this.con.getProp("IP") + ":" + this.con.getProp("port") 
            + "/merlininventorydatabase";;
    private final String f_user = con.getProp("username");
    private final String f_pass = con.getProp("password");
    private DecimalHelper decHelp = new DecimalHelper();
    private DateHelper dateHelp = new DateHelper();
    private Computation calculate = new Computation();
    private SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");

    public void updateCombo(JComboBox<String> combo) {
        try {
            combo.removeAllItems();
            Connection connect = DriverManager.getConnection(this.driver, this.f_user, this.f_pass);
            Statement state = connect.createStatement();
            String query = "Select branch_name from merlininventorydatabase.branch_info";
            ResultSet rset = state.executeQuery(query);
            while (rset.next()) {
                combo.addItem(rset.getString(1));
            }
            state.close();
            connect.close();
            combo.setSelectedItem(this.con.getProp("branch"));
        } catch (SQLException ex) {
            this.con.saveProp("mpis_last_error", String.valueOf(ex));
            Logger.getLogger(Additionals.class.getName()).log(Level.SEVERE, (String) null, ex);
        }
}
    
    
    public void updateCombos() {
        updateCombo(this.tempBranch);
        this.tempProcessedBy.setText(this.con.getProp("last_username"));
    }
    
    public void requestFocusInName() {
        tempClientName.requestFocusInWindow();
    }
    
    public void fill_constants(String name, String add, String contact, String item, String classification) {
/*   79 */     clearFieldsInNewPledgeLoan();
/*   80 */     this.tempClientName.setText(name);
/*   81 */     this.tempClientAddress.setText(add);
/*   82 */     this.tempContactNo.setText(contact);
/*   83 */     this.tempItemDesc.setText(item);
/*   84 */     this.tempClassification.setSelectedItem(classification);
    }
    
    public void clearFieldsInNewPledgeLoan() {
/*   88 */     this.tempClientName.setText("");
/*   89 */     this.tempClientAddress.setText("");
/*   90 */     this.tempItemDesc.setText("");
/*   91 */     this.tempRemarks.setText("");
/*   92 */     this.tempPapNum.setText("");
/*   93 */     this.tempContactNo.setText("");
/*   94 */     this.tempPrincipal.setText("0.00");
/*   95 */     this.aiRateSlider.setValue(0);
/*   96 */     this.tempInterest.setText("0.00");
/*   97 */     this.tempServiceCharge.setText("5.00");
/*   98 */     this.insuranceFee.setText("0.00");
/*   99 */     this.tempTransDate.setDate(Calendar.getInstance().getTime());
/*  100 */     Calendar cal = Calendar.getInstance();
/*  101 */     cal.setTime(this.tempTransDate.getDate());
/*  102 */     this.maturityDatePicker.setDate(this.dateHelp.oneMonth(cal));
/*  103 */     this.expiryDatePicker.setDate(this.dateHelp.threeMonths(cal));
/*  104 */     this.tempContactNo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tempPapNum = new javax.swing.JTextField();
        tempClassification = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tempItemDesc = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tempRemarks = new javax.swing.JTextArea();
        motorInCheckbox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        tempBranch = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tempTransDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        maturityDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel10 = new javax.swing.JLabel();
        expiryDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tempPrincipal = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        tempInterest = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tempServiceCharge = new javax.swing.JTextField();
        insuranceFee = new javax.swing.JTextField();
        tempOtherCharges = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        tempNetProceeds = new javax.swing.JTextField();
        aiRateSlider = new javax.swing.JSlider();
        aiLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        finishNewPledgeBtn = new javax.swing.JButton();
        cancelPledgeActionBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tempClientAddress = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        tempClientName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tempProcessedBy = new javax.swing.JTextField();
        tempContactNo = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(840, 768));

        jPanel5.setPreferredSize(new java.awt.Dimension(820, 768));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane4.setBorder(null);

        jPanel3.setBackground(new java.awt.Color(227, 240, 251));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(227, 240, 251), 1, true));

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Papeleta Number:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Classification:");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Item Description:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Remarks:");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tempPapNum.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempPapNum.setForeground(java.awt.Color.darkGray);
        tempPapNum.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempPapNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempPapNumFocusLost(evt);
            }
        });
        tempPapNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempPapNumKeyPressed(evt);
            }
        });

        tempClassification.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempClassification.setForeground(java.awt.Color.darkGray);
        tempClassification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appliance", "Gadget", "Jewelry", "Vehicle - 2W", "Vehicle - 4W", "Others" }));
        tempClassification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempClassificationActionPerformed(evt);
            }
        });

        tempItemDesc.setColumns(38);
        tempItemDesc.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempItemDesc.setForeground(java.awt.Color.darkGray);
        tempItemDesc.setLineWrap(true);
        tempItemDesc.setRows(3);
        tempItemDesc.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempItemDesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempItemDescFocusLost(evt);
            }
        });
        tempItemDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempItemDescKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tempItemDesc);

        tempRemarks.setColumns(38);
        tempRemarks.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempRemarks.setForeground(java.awt.Color.darkGray);
        tempRemarks.setLineWrap(true);
        tempRemarks.setRows(3);
        tempRemarks.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempRemarks.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempRemarksFocusLost(evt);
            }
        });
        tempRemarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempRemarksKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tempRemarks);

        motorInCheckbox.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        motorInCheckbox.setSelected(true);
        motorInCheckbox.setText("Motor-in");
        motorInCheckbox.setEnabled(false);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Branch:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tempBranch.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempBranch.setForeground(java.awt.Color.darkGray);
        tempBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Transaction Date:");

        tempTransDate.setForeground(new java.awt.Color(51, 51, 51));
        tempTransDate.setToolTipText("");
        tempTransDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempTransDateActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Maturity Date:");

        maturityDatePicker.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Expiry Date:");

        expiryDatePicker.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tempClassification, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(motorInCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempPapNum, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tempTransDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(maturityDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(expiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(tempBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {maturityDatePicker, tempTransDate});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tempTransDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maturityDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tempPapNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)))
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempClassification, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motorInCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {expiryDatePicker, maturityDatePicker, tempTransDate});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel13, jLabel14, jLabel4});

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(227, 240, 251));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(227, 240, 251), 1, true));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Princpal (in Pesos):");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Adv. Int. Rate(%)");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Interest (in Pesos):");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tempPrincipal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempPrincipal.setForeground(java.awt.Color.darkGray);
        tempPrincipal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tempPrincipal.setText("0.00");
        tempPrincipal.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempPrincipal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tempPrincipalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempPrincipalFocusLost(evt);
            }
        });
        tempPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempPrincipalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tempPrincipalKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Service Charge (in Pesos):");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tempInterest.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempInterest.setForeground(java.awt.Color.darkGray);
        tempInterest.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tempInterest.setText("0.00");
        tempInterest.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempInterest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tempInterestFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempInterestFocusLost(evt);
            }
        });
        tempInterest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempInterestKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tempInterestKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Insurance Fee (in Pesos):");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Other Charges (in Pesos):");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tempServiceCharge.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempServiceCharge.setForeground(java.awt.Color.darkGray);
        tempServiceCharge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tempServiceCharge.setText("0.00");
        tempServiceCharge.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempServiceCharge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tempServiceChargeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempServiceChargeFocusLost(evt);
            }
        });
        tempServiceCharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempServiceChargeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tempServiceChargeKeyTyped(evt);
            }
        });

        insuranceFee.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        insuranceFee.setForeground(java.awt.Color.darkGray);
        insuranceFee.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        insuranceFee.setText("0.00");
        insuranceFee.setMargin(new java.awt.Insets(2, 20, 2, 20));
        insuranceFee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                insuranceFeeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                insuranceFeeFocusLost(evt);
            }
        });
        insuranceFee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                insuranceFeeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                insuranceFeeKeyTyped(evt);
            }
        });

        tempOtherCharges.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempOtherCharges.setForeground(java.awt.Color.darkGray);
        tempOtherCharges.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tempOtherCharges.setText("0.00");
        tempOtherCharges.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempOtherCharges.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tempOtherChargesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempOtherChargesFocusLost(evt);
            }
        });
        tempOtherCharges.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempOtherChargesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tempOtherChargesKeyTyped(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Net Proceeds:");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tempNetProceeds.setBackground(new java.awt.Color(119, 179, 212));
        tempNetProceeds.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tempNetProceeds.setForeground(new java.awt.Color(255, 255, 255));
        tempNetProceeds.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tempNetProceeds.setText("0.00");
        tempNetProceeds.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(119, 179, 212), 1, true));
        tempNetProceeds.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempNetProceeds.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tempNetProceedsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempNetProceedsFocusLost(evt);
            }
        });
        tempNetProceeds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempNetProceedsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tempNetProceedsKeyTyped(evt);
            }
        });

        aiRateSlider.setMaximum(15);
        aiRateSlider.setMinorTickSpacing(1);
        aiRateSlider.setPaintLabels(true);
        aiRateSlider.setPaintTicks(true);
        aiRateSlider.setSnapToTicks(true);
        aiRateSlider.setValue(5);
        aiRateSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aiRateSliderStateChanged(evt);
            }
        });

        aiLable.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        aiLable.setForeground(java.awt.Color.darkGray);
        aiLable.setText("0%");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("New Loan Computation");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(aiRateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aiLable, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tempOtherCharges, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(insuranceFee, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tempServiceCharge, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tempInterest, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tempPrincipal, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tempNetProceeds))
                .addGap(20, 20, 20))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel20});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addComponent(tempPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aiRateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aiLable, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(1, 1, 1)
                .addComponent(tempInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(1, 1, 1)
                .addComponent(tempServiceCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(1, 1, 1)
                .addComponent(insuranceFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(1, 1, 1)
                .addComponent(tempOtherCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempNetProceeds, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {insuranceFee, tempInterest, tempOtherCharges, tempPrincipal, tempServiceCharge});

        finishNewPledgeBtn.setBackground(new java.awt.Color(79, 119, 141));
        finishNewPledgeBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        finishNewPledgeBtn.setForeground(new java.awt.Color(255, 255, 255));
        finishNewPledgeBtn.setText("Finish");
        finishNewPledgeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishNewPledgeBtnActionPerformed(evt);
            }
        });

        cancelPledgeActionBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        cancelPledgeActionBtn.setForeground(new java.awt.Color(79, 119, 141));
        cancelPledgeActionBtn.setText("Back to Main Menu");
        cancelPledgeActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPledgeActionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelPledgeActionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(finishNewPledgeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finishNewPledgeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelPledgeActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(227, 240, 251));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(227, 240, 251), 1, true));
        jPanel1.setForeground(new java.awt.Color(173, 219, 255));

        tempClientAddress.setColumns(36);
        tempClientAddress.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempClientAddress.setForeground(java.awt.Color.darkGray);
        tempClientAddress.setLineWrap(true);
        tempClientAddress.setRows(2);
        tempClientAddress.setText("0134 Vicente Ramos St. San Pedro, Bustos, Bulacan");
        tempClientAddress.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempClientAddress.setMinimumSize(new java.awt.Dimension(250, 60));
        tempClientAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tempClientAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempClientAddressFocusLost(evt);
            }
        });
        tempClientAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempClientAddressKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tempClientAddressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tempClientAddress);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Name");

        tempClientName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempClientName.setForeground(java.awt.Color.darkGray);
        tempClientName.setText("Lucky E. Cruz");
        tempClientName.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempClientName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tempClientNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempClientNameFocusLost(evt);
            }
        });
        tempClientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempClientNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tempClientNameKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Address: ");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Contact No.:");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Processed by:");

        tempProcessedBy.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempProcessedBy.setForeground(java.awt.Color.darkGray);
        tempProcessedBy.setMargin(new java.awt.Insets(2, 20, 2, 20));
        tempProcessedBy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tempProcessedByFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempProcessedByFocusLost(evt);
            }
        });
        tempProcessedBy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempProcessedByKeyPressed(evt);
            }
        });

        tempContactNo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        tempContactNo.setForeground(java.awt.Color.darkGray);
        tempContactNo.setText("09175098926");
        tempContactNo.setMargin(new java.awt.Insets(2, 10, 2, 10));
        tempContactNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tempContactNoFocusLost(evt);
            }
        });
        tempContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempContactNoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tempContactNoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(tempClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tempContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempProcessedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempProcessedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel6);

        jPanel5.add(jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tempClientNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempClientNameFocusLost
        tempClientName.setText(this.tempClientName.getText().trim());
    }//GEN-LAST:event_tempClientNameFocusLost

    private void tempClientNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempClientNameFocusGained
        tempClientName.selectAll();
    }//GEN-LAST:event_tempClientNameFocusGained

    private void tempClientNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempClientNameKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
            this.tempClientAddress.requestFocusInWindow();
            this.tempClientAddress.selectAll();
        }
    }//GEN-LAST:event_tempClientNameKeyPressed

    private void tempClientNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempClientNameKeyTyped
        if (this.tempClientName.getText().length() > 75 || evt.getKeyChar() == '\'')
        evt.consume(); 
    }//GEN-LAST:event_tempClientNameKeyTyped

    private void tempClientAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempClientAddressFocusGained
        tempClientAddress.selectAll();
    }//GEN-LAST:event_tempClientAddressFocusGained

    private void tempClientAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempClientAddressFocusLost
        this.tempClientAddress.setText(this.tempClientAddress.getText().trim());
        this.tempClientAddress.setText(this.tempClientAddress.getText().replace("\r", "").replace("\n", ""));
    }//GEN-LAST:event_tempClientAddressFocusLost

    private void tempClientAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempClientAddressKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
            this.tempContactNo.requestFocusInWindow();
            this.tempContactNo.selectAll();
        } 
    }//GEN-LAST:event_tempClientAddressKeyPressed

    private void tempClientAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempClientAddressKeyTyped
        if (this.tempClientAddress.getText().length() > 75 || evt.getKeyChar() == '\'') {
/*  834 */       evt.consume();
     }
    }//GEN-LAST:event_tempClientAddressKeyTyped

    private void tempContactNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempContactNoFocusLost
        this.tempContactNo.setText(this.tempContactNo.getText().trim());
    }//GEN-LAST:event_tempContactNoFocusLost

    private void tempContactNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempContactNoKeyPressed
        int key = evt.getKeyCode();
/*  847 */     if (key == 10) {
/*  848 */       this.tempProcessedBy.requestFocusInWindow();
/*  849 */       this.tempProcessedBy.selectAll();
     } 
    }//GEN-LAST:event_tempContactNoKeyPressed

    private void tempContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempContactNoKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || this.tempContactNo.getText().length() > 15)
/*  855 */       evt.consume(); 
    }//GEN-LAST:event_tempContactNoKeyTyped

    private void tempProcessedByFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempProcessedByFocusGained
        this.tempProcessedBy.selectAll();
    }//GEN-LAST:event_tempProcessedByFocusGained

    private void tempProcessedByFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempProcessedByFocusLost
        this.tempProcessedBy.setText(this.tempProcessedBy.getText().trim());
    }//GEN-LAST:event_tempProcessedByFocusLost

    private void tempProcessedByKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempProcessedByKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
            this.tempPapNum.requestFocusInWindow();
            this.tempPapNum.selectAll();
        } 
    }//GEN-LAST:event_tempProcessedByKeyPressed

    private void tempPapNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempPapNumFocusLost
        this.tempPapNum.setText(this.tempPapNum.getText().trim());
    }//GEN-LAST:event_tempPapNumFocusLost

    private void tempItemDescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempItemDescFocusLost
        this.tempItemDesc.setText(this.tempItemDesc.getText().trim());
        this.tempItemDesc.setText(this.tempItemDesc.getText().replace("\r", "").replace("\n", ""));
    }//GEN-LAST:event_tempItemDescFocusLost

    private void tempRemarksFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempRemarksFocusLost
        this.tempRemarks.setText(this.tempRemarks.getText().trim());
        this.tempRemarks.setText(this.tempRemarks.getText().replace("\r", "").replace("\n", ""));
    }//GEN-LAST:event_tempRemarksFocusLost

    private void tempTransDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempTransDateActionPerformed
        Calendar cal = Calendar.getInstance();
/*  894 */     cal.setTime(this.tempTransDate.getDate());
/*  895 */     this.maturityDatePicker.setDate(this.dateHelp.oneMonth(cal));
/*  896 */     this.expiryDatePicker.setDate(this.dateHelp.threeMonths(cal));
    }//GEN-LAST:event_tempTransDateActionPerformed

    private void tempRemarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempRemarksKeyPressed
        int key = evt.getKeyCode();
/*  901 */     if (key == 10) {
/*  902 */       this.tempTransDate.requestFocusInWindow();
     }
    }//GEN-LAST:event_tempRemarksKeyPressed

    private void tempPapNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempPapNumKeyPressed
        int key = evt.getKeyCode();
/*  908 */     if (key == 10) {
/*  909 */       this.tempItemDesc.requestFocusInWindow();
/*  910 */       this.tempItemDesc.selectAll();
     } 
    }//GEN-LAST:event_tempPapNumKeyPressed

    private void tempItemDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempItemDescKeyPressed
        int key = evt.getKeyCode();
/*  916 */     if (key == 10) {
/*  917 */       this.tempRemarks.requestFocusInWindow();
/*  918 */       this.tempRemarks.selectAll();
     } 
    }//GEN-LAST:event_tempItemDescKeyPressed

    private void tempPrincipalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempPrincipalFocusLost
        this.tempPrincipal.setText(this.decHelp.FormatNumber(Double.parseDouble(this.tempPrincipal.getText().replace(",", ""))));
        if (Double.parseDouble(this.tempPrincipal.getText().replace(",", "")) > 0.0D && Double.parseDouble(this.tempServiceCharge.getText().replace(",", "")) < 0.0D) {
            this.tempServiceCharge.setText("5.00");
        }
        this.insuranceFee.setText(this.calculate.computeInsurance(Double.parseDouble
            (this.tempPrincipal.getText().replace(",", ""))));
        this.tempInterest.setText(this.calculate.computeAdvanceInterest
            (Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), 
                Double.valueOf(this.aiRateSlider.getValue())));
        this.tempNetProceeds.setText(this.calculate.computeNetProceeds
            (Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), 
                Double.valueOf(this.aiRateSlider.getValue()), 
                Double.parseDouble(this.tempServiceCharge.getText().replace(",", "")), 
                Double.parseDouble(this.tempOtherCharges.getText().replace(",", "")), 
                Double.parseDouble(this.insuranceFee.getText().replace(",", ""))));
    }//GEN-LAST:event_tempPrincipalFocusLost

    private void tempPrincipalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempPrincipalFocusGained
        tempPrincipal.selectAll();
    }//GEN-LAST:event_tempPrincipalFocusGained

    private void tempPrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempPrincipalKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
                this.tempServiceCharge.requestFocusInWindow();
                this.tempServiceCharge.selectAll();

            this.tempPrincipal.setText(this.decHelp.FormatNumber(Double.parseDouble(this.tempPrincipal.getText().replace(",", ""))));
            this.tempInterest.setText(this.calculate.computeAdvanceInterest(Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), 
                    Double.valueOf(this.aiRateSlider.getValue())));
            this.tempNetProceeds.setText(this.calculate.computeNetProceeds(Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), 
                    Double.valueOf(this.aiRateSlider.getValue()), Double.parseDouble(this.tempServiceCharge.getText().replace(",", "")), Double.parseDouble(this.insuranceFee.getText().replace(",", "")), 0.0D));
        } 
    }//GEN-LAST:event_tempPrincipalKeyPressed

    private void tempPrincipalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempPrincipalKeyTyped
        if ((!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') || this.tempPrincipal.getText().replace(",", "").length() > 10)
            evt.consume(); 
    }//GEN-LAST:event_tempPrincipalKeyTyped

    private void tempInterestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempInterestKeyTyped
        if ((!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') || this.tempInterest.getText().replace(",", "").length() > 10)
/* 1009 */       evt.consume();
    }//GEN-LAST:event_tempInterestKeyTyped

    private void tempServiceChargeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempServiceChargeKeyTyped
        if ((!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') || this.tempServiceCharge.getText().replace(",", "").length() > 8)
/* 1014 */       evt.consume(); 
    }//GEN-LAST:event_tempServiceChargeKeyTyped

    private void insuranceFeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insuranceFeeKeyTyped
        if ((!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') || this.insuranceFee.getText().replace(",", "").length() > 10)
/* 1019 */       evt.consume();
    }//GEN-LAST:event_insuranceFeeKeyTyped

    private void tempOtherChargesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempOtherChargesKeyTyped
        if ((!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') || this.tempOtherCharges.getText().replace(",", "").length() > 10)
/* 1024 */       evt.consume();
    }//GEN-LAST:event_tempOtherChargesKeyTyped

    private void tempInterestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempInterestKeyPressed
        int key = evt.getKeyCode();
/* 1029 */     if (key == 10) {
/* 1030 */       this.tempServiceCharge.requestFocusInWindow();
/* 1031 */       this.tempServiceCharge.selectAll();
     } 
    }//GEN-LAST:event_tempInterestKeyPressed

    private void tempServiceChargeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempServiceChargeKeyPressed
        int key = evt.getKeyCode();
/* 1037 */     if (key == 10) {
/* 1038 */       this.insuranceFee.requestFocusInWindow();
/* 1039 */       this.insuranceFee.selectAll();
     } 
    }//GEN-LAST:event_tempServiceChargeKeyPressed

    private void insuranceFeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insuranceFeeKeyPressed
        int key = evt.getKeyCode();
/* 1045 */     if (key == 10)
/* 1046 */       this.tempOtherCharges.requestFocusInWindow(); 
    }//GEN-LAST:event_insuranceFeeKeyPressed

    private void tempOtherChargesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempOtherChargesKeyPressed
         int key = evt.getKeyCode();
/* 1051 */     if (key == 10)
/* 1052 */       this.finishNewPledgeBtn.requestFocusInWindow();
    }//GEN-LAST:event_tempOtherChargesKeyPressed

    private void tempInterestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempInterestFocusLost
        this.tempInterest.setText(this.decHelp.FormatNumber(Double.parseDouble(this.tempInterest.getText().replace(",", ""))));
/* 1057 */     this.aiRateSlider.setValue(Integer.parseInt(this.calculate.computeAdvanceInterestRate(Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), Double.parseDouble(this.tempInterest.getText().replace(",", "")))));
/* 1058 */     this.tempNetProceeds.setText(this.calculate.computeNetProceeds(Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), Double.valueOf(this.aiRateSlider.getValue()), Double.parseDouble(this.tempServiceCharge.getText().replace(",", "")), Double.parseDouble(this.tempOtherCharges.getText().replace(",", "")), Double.parseDouble(this.insuranceFee.getText().replace(",", ""))));
    }//GEN-LAST:event_tempInterestFocusLost

    private void tempServiceChargeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempServiceChargeFocusLost
        this.tempServiceCharge.setText(this.decHelp.FormatNumber(Double.parseDouble(this.tempServiceCharge.getText().replace(",", ""))));
/* 1063 */     this.tempNetProceeds.setText(this.calculate.computeNetProceeds(Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), Double.valueOf(this.aiRateSlider.getValue()), Double.parseDouble(this.tempServiceCharge.getText().replace(",", "")), Double.parseDouble(this.tempOtherCharges.getText().replace(",", "")), Double.parseDouble(this.insuranceFee.getText().replace(",", ""))));
    }//GEN-LAST:event_tempServiceChargeFocusLost

    private void insuranceFeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_insuranceFeeFocusLost
        this.insuranceFee.setText(this.decHelp.FormatNumber(Double.parseDouble(this.insuranceFee.getText().replace(",", ""))));
/* 1068 */     this.tempNetProceeds.setText(this.calculate.computeNetProceeds(Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), Double.valueOf(this.aiRateSlider.getValue()), Double.parseDouble(this.tempServiceCharge.getText().replace(",", "")), Double.parseDouble(this.tempOtherCharges.getText().replace(",", "")), Double.parseDouble(this.insuranceFee.getText().replace(",", ""))));
   
    }//GEN-LAST:event_insuranceFeeFocusLost

    private void tempOtherChargesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempOtherChargesFocusLost
        this.tempOtherCharges.setText(this.decHelp.FormatNumber(Double.parseDouble(this.tempOtherCharges.getText().replace(",", ""))));
/* 1073 */     this.tempNetProceeds.setText(this.calculate.computeNetProceeds(Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), Double.valueOf(this.aiRateSlider.getValue()), Double.parseDouble(this.tempServiceCharge.getText().replace(",", "")), Double.parseDouble(this.tempOtherCharges.getText().replace(",", "")), Double.parseDouble(this.insuranceFee.getText().replace(",", ""))));
   
    }//GEN-LAST:event_tempOtherChargesFocusLost

    private void tempInterestFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempInterestFocusGained
        tempInterest.selectAll();
    }//GEN-LAST:event_tempInterestFocusGained

    private void tempServiceChargeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempServiceChargeFocusGained
        tempServiceCharge.selectAll();
    }//GEN-LAST:event_tempServiceChargeFocusGained

    private void insuranceFeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_insuranceFeeFocusGained
        insuranceFee.selectAll();
    }//GEN-LAST:event_insuranceFeeFocusGained

    private void tempOtherChargesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempOtherChargesFocusGained
        tempOtherCharges.selectAll();
    }//GEN-LAST:event_tempOtherChargesFocusGained

    private void finishNewPledgeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishNewPledgeBtnActionPerformed
        Sangla newLoan = new Sangla();
    newLoan.setPap_num(this.tempPapNum.getText());
    newLoan.setBranch(this.tempBranch.getSelectedItem().toString());
    newLoan.setItemCodes();
    newLoan.setClient_name(this.tempClientName.getText());
    newLoan.setClient_address(this.tempClientAddress.getText());
    newLoan.setContact_no(this.tempContactNo.getText());
    newLoan.setProcessed_by(this.tempProcessedBy.getText());
    newLoan.setItem_description(this.tempItemDesc.getText());
    newLoan.setClassification(this.tempClassification.getSelectedItem().toString());
    newLoan.setTransaction_date(this.dateFormatter.format(this.tempTransDate.getDate()));
    newLoan.setOld_pap_num("N/A");
    newLoan.setNew_pap_num(null);
    newLoan.setStatus("Open");
    newLoan.setRemarks(this.tempRemarks.getText());
    newLoan.setPrincipal(Double.parseDouble(this.tempPrincipal.getText().replace(",", "")));
    newLoan.setAdvance_interest(Double.parseDouble(this.tempInterest.getText().replace(",", "")));
    newLoan.setAdvance_interest_rate(Double.valueOf(this.aiRateSlider.getValue()));
    newLoan.setInterest(0.0D);
    newLoan.setInterest_rate(0.0D);
    newLoan.setInsurance(Double.parseDouble(this.insuranceFee.getText().replace(",", "")));
    newLoan.setService_charge(Double.parseDouble(this.tempServiceCharge.getText().replace(",", "")));
    newLoan.setOther_charges(Double.parseDouble(this.tempOtherCharges.getText().replace(",", "")));
    newLoan.setNet_proceeds(Double.parseDouble(this.tempNetProceeds.getText().replace(",", "")));
    ViewNewAddedItem showNewItemDialogue = new ViewNewAddedItem(null, true, newLoan);
    showNewItemDialogue.setVisible(true);
    if (this.tempClientName.getText().isEmpty() || this.tempClientAddress.getText().isEmpty() || this.tempItemDesc.getText().isEmpty() || this.tempContactNo.getText().isEmpty() || this.tempPapNum.getText().isEmpty() || this.tempPrincipal.getText().replace(",", "").isEmpty() || this.tempInterest.getText().replace(",", "").isEmpty() || this.tempServiceCharge.getText().replace(",", "").isEmpty() || this.insuranceFee.getText().replace(",", "").isEmpty()) {
      JOptionPane.showMessageDialog(null, "Please complete all information.", "New Pledge Loan", 0);
    } else if (showNewItemDialogue.allowAddToDatabase()) {
      newLoan.insertToClienInfo();
      newLoan.saveToEmpeno();
      if (!newLoan.isInsertToClientStatus()) {
        JOptionPane.showMessageDialog(null, "There has been an error in updating the Client Information Table. Please retry. \n If problem persists, contact the database administrator.", "Error!", 0);
      } else {
        JOptionPane.showMessageDialog(null, "Item added successfully!", "New Pledge Loan", 1);
        CashTransactions newLoanCashTrans = new CashTransactions();
        newLoanCashTrans.setDatabase("cashtransactions");
        newLoanCashTrans.setCash_transaction_type("NEW");
        newLoanCashTrans.setLoans_item_code(newLoan.getItem_code_a());
        newLoanCashTrans.setLoans_name(this.tempClientName.getText());
        newLoanCashTrans.setTransaction_amount(Double.parseDouble(this.tempNetProceeds.getText().replace(",", "")));
        newLoanCashTrans.setBranch(this.tempBranch.getSelectedItem().toString());
        newLoanCashTrans.setTransaction_remarks("New Loan ");
        int tableRowCount = 0;
        try {
          Connection connect = DriverManager.getConnection(this.driver, this.f_user, this.f_pass);
          Statement query0 = connect.createStatement();
          ResultSet rSet = query0.executeQuery("Select COUNT(*) from cashtransactions.new_loans");
          while (rSet.next())
            tableRowCount = rSet.getInt(1); 
          tableRowCount++;
          System.out.println(tableRowCount);
        } catch (SQLException ex) {
          this.con.saveProp("mpis_last_error", String.valueOf(ex));
          System.out.println("error in count search");
        } 
        newLoanCashTrans.setTransaction_no(tableRowCount);
        newLoanCashTrans.generateTransaction_id();
        newLoanCashTrans.generateTransaction_remarks();
        System.out.println(newLoanCashTrans.getTransaction_id());
        System.out.println(newLoanCashTrans.getTransaction_remarks());
        newLoanCashTrans.addNewLoanTransactionToDB();
        newLoanCashTrans.addToDailyTransaction();
        if (!newLoanCashTrans.isNewloan_inserted()) {
          System.out.println("There has been an error inserting this transaction to the database");
        } else {
          newLoanCashTrans.addToDailyTransaction();
        } 
        clearFieldsInNewPledgeLoan();
      } 
    }  
    }//GEN-LAST:event_finishNewPledgeBtnActionPerformed

    private void cancelPledgeActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPledgeActionBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelPledgeActionBtnActionPerformed

    private void tempClassificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempClassificationActionPerformed
        if (tempClassification.getSelectedItem().toString().equalsIgnoreCase("Vehicle-2W") || tempClassification.getSelectedItem().toString().equalsIgnoreCase("Vehicle-4W")) {
            motorInCheckbox.setEnabled(true);
        } else {
            motorInCheckbox.setEnabled(false);
        }
    }//GEN-LAST:event_tempClassificationActionPerformed

    private void tempNetProceedsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempNetProceedsFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tempNetProceedsFocusGained

    private void tempNetProceedsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tempNetProceedsFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tempNetProceedsFocusLost

    private void tempNetProceedsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempNetProceedsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempNetProceedsKeyPressed

    private void tempNetProceedsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempNetProceedsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tempNetProceedsKeyTyped

    private void aiRateSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aiRateSliderStateChanged
        aiLable.setText(Integer.toString(aiRateSlider.getValue()).concat("%"));
        this.tempInterest.setText(this.calculate.computeAdvanceInterest(Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), 
                Double.valueOf(this.aiRateSlider.getValue())));
        this.tempNetProceeds.setText(this.calculate.computeNetProceeds(Double.parseDouble(this.tempPrincipal.getText().replace(",", "")), 
                Double.valueOf(this.aiRateSlider.getValue()), 
                Double.parseDouble(this.tempServiceCharge.getText().replace(",", "")), 
                Double.parseDouble(this.tempOtherCharges.getText().replace(",", "")), 
                Double.parseDouble(this.insuranceFee.getText().replace(",", ""))));
    }//GEN-LAST:event_aiRateSliderStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aiLable;
    private javax.swing.JSlider aiRateSlider;
    private javax.swing.JButton cancelPledgeActionBtn;
    private org.jdesktop.swingx.JXDatePicker expiryDatePicker;
    private javax.swing.JButton finishNewPledgeBtn;
    private javax.swing.JTextField insuranceFee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private org.jdesktop.swingx.JXDatePicker maturityDatePicker;
    private javax.swing.JCheckBox motorInCheckbox;
    private javax.swing.JComboBox<String> tempBranch;
    private javax.swing.JComboBox<String> tempClassification;
    private javax.swing.JTextArea tempClientAddress;
    private javax.swing.JTextField tempClientName;
    private javax.swing.JTextField tempContactNo;
    private javax.swing.JTextField tempInterest;
    private javax.swing.JTextArea tempItemDesc;
    private javax.swing.JTextField tempNetProceeds;
    private javax.swing.JTextField tempOtherCharges;
    private javax.swing.JTextField tempPapNum;
    private javax.swing.JTextField tempPrincipal;
    private javax.swing.JTextField tempProcessedBy;
    private javax.swing.JTextArea tempRemarks;
    private javax.swing.JTextField tempServiceCharge;
    private org.jdesktop.swingx.JXDatePicker tempTransDate;
    // End of variables declaration//GEN-END:variables
}
