/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpis_mariadb_2;

/**
 *
 * @author Lucky
 */
public class ViewMode extends javax.swing.JDialog {

    /**
     * Creates new form ViewMode
     */
    public ViewMode(java.awt.Frame parent, boolean modal, Sangla newLoan) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
/*  32 */     DecimalHelper decHelp = new DecimalHelper();
/*     */     
/*  34 */     this.papeletaNoVM.setText(newLoan.getPap_num());
/*  35 */     this.oldPapNoVM.setText(newLoan.getOld_pap_num());
/*  36 */     this.newPapNoVM.setText(newLoan.getNew_pap_num());
/*  37 */     this.clientNameVM.setText(newLoan.getClient_name());
/*  38 */     this.clientAddressVM.setText(newLoan.getClient_address());
/*  39 */     this.itemDescVM.setText(newLoan.getItem_description());
/*  40 */     this.branchVM.setText(newLoan.getBranch());
/*  41 */     this.itemClassificationVM.setText(newLoan.getClassification());
/*  42 */     this.processedByVM.setText(newLoan.getProcessed_by());
/*  43 */     this.transactionDateVM.setText(newLoan.getTransaction_date());
/*  44 */     this.maturityDateVM.setText(newLoan.getMaturity_date());
/*  45 */     this.expiryDateVM.setText(newLoan.getExpiration_date());
/*  46 */     this.principalVM.setText(decHelp.FormatNumber(newLoan.getPrincipal()));
/*  47 */     this.interestVM.setText(decHelp.FormatPercent(newLoan.getAdvance_interest()));
/*  48 */     this.insurancetVM.setText(decHelp.FormatNumber(newLoan.getInsurance()));
/*  49 */     this.serviceChargeVM.setText(decHelp.FormatNumber(newLoan.getService_charge()));
/*  50 */     this.otherChargesVM.setText(decHelp.FormatNumber(newLoan.getOther_charges()));
/*  51 */     this.netProceedsVM.setText(decHelp.FormatNumber(newLoan.getNet_proceeds()));
/*  52 */     this.statusVM.setText(newLoan.getStatus());
/*  53 */     this.remarksVM.setText(newLoan.getRemarks());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        papeletaNoVM = new javax.swing.JTextField();
        oldPapNoVM = new javax.swing.JTextField();
        clientNameVM = new javax.swing.JTextField();
        statusVM = new javax.swing.JTextField();
        newPapNoVM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientAddressVM = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemDescVM = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        remarksVM = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        branchVM = new javax.swing.JTextField();
        itemClassificationVM = new javax.swing.JTextField();
        processedByVM = new javax.swing.JTextField();
        transactionDateVM = new javax.swing.JTextField();
        maturityDateVM = new javax.swing.JTextField();
        expiryDateVM = new javax.swing.JTextField();
        principalVM = new javax.swing.JTextField();
        interestVM = new javax.swing.JTextField();
        insurancetVM = new javax.swing.JTextField();
        serviceChargeVM = new javax.swing.JTextField();
        otherChargesVM = new javax.swing.JTextField();
        netProceedsVM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(79, 119, 141));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(239, 246, 250));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(137, 164, 179), 3, true));

        jLabel1.setBackground(new java.awt.Color(239, 246, 250));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 119, 141));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Merlin Pawn Management System");
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(239, 246, 250));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Loan No.");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Old Loan No.");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Client Name");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Client Address");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Status");

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("New Loan No.");

        papeletaNoVM.setEditable(false);
        papeletaNoVM.setBackground(new java.awt.Color(255, 255, 255));
        papeletaNoVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        papeletaNoVM.setForeground(new java.awt.Color(51, 51, 51));

        oldPapNoVM.setEditable(false);
        oldPapNoVM.setBackground(new java.awt.Color(255, 255, 255));
        oldPapNoVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        oldPapNoVM.setForeground(new java.awt.Color(51, 51, 51));

        clientNameVM.setEditable(false);
        clientNameVM.setBackground(new java.awt.Color(255, 255, 255));
        clientNameVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        clientNameVM.setForeground(new java.awt.Color(51, 51, 51));

        statusVM.setEditable(false);
        statusVM.setBackground(new java.awt.Color(255, 255, 255));
        statusVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        statusVM.setForeground(new java.awt.Color(51, 51, 51));

        newPapNoVM.setEditable(false);
        newPapNoVM.setBackground(new java.awt.Color(255, 255, 255));
        newPapNoVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        newPapNoVM.setForeground(new java.awt.Color(51, 51, 51));

        clientAddressVM.setEditable(false);
        clientAddressVM.setBackground(new java.awt.Color(255, 255, 255));
        clientAddressVM.setColumns(20);
        clientAddressVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        clientAddressVM.setForeground(new java.awt.Color(51, 51, 51));
        clientAddressVM.setLineWrap(true);
        clientAddressVM.setRows(2);
        jScrollPane1.setViewportView(clientAddressVM);

        itemDescVM.setEditable(false);
        itemDescVM.setBackground(new java.awt.Color(255, 255, 255));
        itemDescVM.setColumns(20);
        itemDescVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        itemDescVM.setForeground(new java.awt.Color(51, 51, 51));
        itemDescVM.setLineWrap(true);
        itemDescVM.setRows(3);
        itemDescVM.setWrapStyleWord(true);
        jScrollPane2.setViewportView(itemDescVM);

        remarksVM.setEditable(false);
        remarksVM.setBackground(new java.awt.Color(255, 255, 255));
        remarksVM.setColumns(20);
        remarksVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        remarksVM.setForeground(new java.awt.Color(51, 51, 51));
        remarksVM.setLineWrap(true);
        remarksVM.setRows(2);
        remarksVM.setWrapStyleWord(true);
        jScrollPane3.setViewportView(remarksVM);

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Branch");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Classification");

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Processed By");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Transaction Date");

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Maturity Date");

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Expiry Date");

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Principal");

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Advance Interest");

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Insurance");

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Service Charge");

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Other Charges");

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Net Proceeds");

        branchVM.setEditable(false);
        branchVM.setBackground(new java.awt.Color(255, 255, 255));
        branchVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        branchVM.setForeground(new java.awt.Color(51, 51, 51));

        itemClassificationVM.setEditable(false);
        itemClassificationVM.setBackground(new java.awt.Color(255, 255, 255));
        itemClassificationVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        itemClassificationVM.setForeground(new java.awt.Color(51, 51, 51));

        processedByVM.setEditable(false);
        processedByVM.setBackground(new java.awt.Color(255, 255, 255));
        processedByVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        processedByVM.setForeground(new java.awt.Color(51, 51, 51));

        transactionDateVM.setEditable(false);
        transactionDateVM.setBackground(new java.awt.Color(255, 255, 255));
        transactionDateVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        transactionDateVM.setForeground(new java.awt.Color(51, 51, 51));

        maturityDateVM.setEditable(false);
        maturityDateVM.setBackground(new java.awt.Color(255, 255, 255));
        maturityDateVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        maturityDateVM.setForeground(new java.awt.Color(51, 51, 51));

        expiryDateVM.setEditable(false);
        expiryDateVM.setBackground(new java.awt.Color(255, 255, 255));
        expiryDateVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        expiryDateVM.setForeground(new java.awt.Color(51, 51, 51));

        principalVM.setEditable(false);
        principalVM.setBackground(new java.awt.Color(255, 255, 255));
        principalVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        principalVM.setForeground(new java.awt.Color(51, 51, 51));

        interestVM.setEditable(false);
        interestVM.setBackground(new java.awt.Color(255, 255, 255));
        interestVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        interestVM.setForeground(new java.awt.Color(51, 51, 51));

        insurancetVM.setEditable(false);
        insurancetVM.setBackground(new java.awt.Color(255, 255, 255));
        insurancetVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        insurancetVM.setForeground(new java.awt.Color(51, 51, 51));

        serviceChargeVM.setEditable(false);
        serviceChargeVM.setBackground(new java.awt.Color(255, 255, 255));
        serviceChargeVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        serviceChargeVM.setForeground(new java.awt.Color(51, 51, 51));

        otherChargesVM.setEditable(false);
        otherChargesVM.setBackground(new java.awt.Color(255, 255, 255));
        otherChargesVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        otherChargesVM.setForeground(new java.awt.Color(51, 51, 51));

        netProceedsVM.setEditable(false);
        netProceedsVM.setBackground(new java.awt.Color(255, 255, 255));
        netProceedsVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        netProceedsVM.setForeground(new java.awt.Color(51, 51, 51));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Item Description");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Remarks");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(papeletaNoVM, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(oldPapNoVM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(newPapNoVM, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                                .addComponent(clientNameVM, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel6)))
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(statusVM, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(branchVM, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemClassificationVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(processedByVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(serviceChargeVM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(transactionDateVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(principalVM))
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(otherChargesVM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(interestVM, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(maturityDateVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel16)))
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)
                            .addComponent(expiryDateVM, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insurancetVM)
                            .addComponent(netProceedsVM))))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {branchVM, expiryDateVM, itemClassificationVM, maturityDateVM, processedByVM, transactionDateVM});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel8, newPapNoVM, oldPapNoVM, papeletaNoVM});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(papeletaNoVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPapNoVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPapNoVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemClassificationVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel11))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(processedByVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maturityDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(principalVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insurancetVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceChargeVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherChargesVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netProceedsVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Merlin Pawnshop, Inc.   All Rights Reserved. © 2011");

        jButton1.setBackground(new java.awt.Color(79, 119, 141));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() { private Sangla newLoan;
            public void run() {
                ViewMode dialog = new ViewMode(new javax.swing.JFrame(), true, this.newLoan);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branchVM;
    private javax.swing.JTextArea clientAddressVM;
    private javax.swing.JTextField clientNameVM;
    private javax.swing.JTextField expiryDateVM;
    private javax.swing.JTextField insurancetVM;
    private javax.swing.JTextField interestVM;
    private javax.swing.JTextField itemClassificationVM;
    private javax.swing.JTextArea itemDescVM;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField maturityDateVM;
    private javax.swing.JTextField netProceedsVM;
    private javax.swing.JTextField newPapNoVM;
    private javax.swing.JTextField oldPapNoVM;
    private javax.swing.JTextField otherChargesVM;
    private javax.swing.JTextField papeletaNoVM;
    private javax.swing.JTextField principalVM;
    private javax.swing.JTextField processedByVM;
    private javax.swing.JTextArea remarksVM;
    private javax.swing.JTextField serviceChargeVM;
    private javax.swing.JTextField statusVM;
    private javax.swing.JTextField transactionDateVM;
    // End of variables declaration//GEN-END:variables
}
