/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpis_mariadb_2;

/**
 *
 * @author Lucky
 */
public class ViewRenewedItem extends javax.swing.JDialog {

    /**
     * Creates new form ViewMode
     */
    public ViewRenewedItem(java.awt.Frame parent, boolean modal, Sangla renewedSangla) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
/*  29 */     DecimalHelper decHelp = new DecimalHelper();
/*  30 */     this.papeletaNoVM.setText(renewedSangla.getPap_num());
/*  31 */     this.clientNameVM.setText(renewedSangla.getClient_name());
/*  32 */     this.clientAddressVM.setText(renewedSangla.getClient_address());
/*  33 */     this.itemDescVM.setText(renewedSangla.getItem_description());
/*  34 */     this.branchVM.setText(renewedSangla.getBranch());
/*  35 */     this.itemClassificationVM.setText(renewedSangla.getClassification());
/*  36 */     this.processedByVM.setText(renewedSangla.getProcessed_by());
/*  37 */     this.transactionDateVM.setText(renewedSangla.getTransaction_date());
/*  38 */     this.maturityDateVM.setText(renewedSangla.getMaturity_date());
/*  39 */     this.expiryDateVM.setText(renewedSangla.getExpiration_date());
/*  40 */     this.principalVM.setText(decHelp.FormatNumber(renewedSangla.getPrincipal()));
/*  41 */     this.interestVM.setText(decHelp.FormatPercent(renewedSangla.getAdvance_interest()));
/*  42 */     this.insurancetVM.setText(decHelp.FormatNumber(renewedSangla.getInsurance()));
/*  43 */     this.serviceChargeVM.setText(decHelp.FormatNumber(renewedSangla.getService_charge()));
/*  44 */     this.otherChargesVM.setText(decHelp.FormatNumber(renewedSangla.getOther_charges()));
/*  45 */     this.netProceedsVM.setText(decHelp.FormatNumber(renewedSangla.getNet_proceeds()));
/*  46 */     this.statusVM.setText("Open");
/*  47 */     this.remarksVM.setText(renewedSangla.getRemarks());
/*  48 */     this.contactNo.setText(renewedSangla.getContact_no());
/*  49 */     this.oldPapNum.setText(renewedSangla.getOld_pap_num());
/*     */     
/*  51 */     this.noButton1.requestFocusInWindow();
    }
    
    private boolean allow;
    
    public boolean allowAddToDatabase() {
/*  55 */     return this.allow;
/*     */   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel45 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        papeletaNoVM = new javax.swing.JTextField();
        clientNameVM = new javax.swing.JTextField();
        statusVM = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        clientAddressVM = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        itemDescVM = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        remarksVM = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        branchVM = new javax.swing.JTextField();
        itemClassificationVM = new javax.swing.JTextField();
        processedByVM = new javax.swing.JTextField();
        transactionDateVM = new javax.swing.JTextField();
        maturityDateVM = new javax.swing.JTextField();
        expiryDateVM = new javax.swing.JTextField();
        principalVM = new javax.swing.JTextField();
        interestVM = new javax.swing.JTextField();
        insurancetVM = new javax.swing.JTextField();
        serviceChargeVM = new javax.swing.JTextField();
        otherChargesVM = new javax.swing.JTextField();
        netProceedsVM = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        contactNo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        oldPapNum = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        yesButton1 = new javax.swing.JButton();
        noButton1 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();

        jLabel45.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 102, 102));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Merlin Pawnshop, Inc.   All Rights Reserved. © 2011");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(239, 246, 250));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 119, 141), 3, true));

        jPanel3.setBackground(new java.awt.Color(239, 246, 250));

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Loan No.");

        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Client Name");

        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Client Address");

        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Status");

        papeletaNoVM.setEditable(false);
        papeletaNoVM.setBackground(new java.awt.Color(255, 255, 255));
        papeletaNoVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        papeletaNoVM.setForeground(new java.awt.Color(51, 51, 51));

        clientNameVM.setEditable(false);
        clientNameVM.setBackground(new java.awt.Color(255, 255, 255));
        clientNameVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        clientNameVM.setForeground(new java.awt.Color(51, 51, 51));

        statusVM.setEditable(false);
        statusVM.setBackground(new java.awt.Color(255, 255, 255));
        statusVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        statusVM.setForeground(new java.awt.Color(51, 51, 51));

        clientAddressVM.setEditable(false);
        clientAddressVM.setBackground(new java.awt.Color(255, 255, 255));
        clientAddressVM.setColumns(20);
        clientAddressVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        clientAddressVM.setForeground(new java.awt.Color(51, 51, 51));
        clientAddressVM.setLineWrap(true);
        clientAddressVM.setRows(2);
        jScrollPane4.setViewportView(clientAddressVM);

        itemDescVM.setEditable(false);
        itemDescVM.setBackground(new java.awt.Color(255, 255, 255));
        itemDescVM.setColumns(20);
        itemDescVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        itemDescVM.setForeground(new java.awt.Color(51, 51, 51));
        itemDescVM.setLineWrap(true);
        itemDescVM.setRows(3);
        itemDescVM.setWrapStyleWord(true);
        jScrollPane5.setViewportView(itemDescVM);

        remarksVM.setEditable(false);
        remarksVM.setBackground(new java.awt.Color(255, 255, 255));
        remarksVM.setColumns(20);
        remarksVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        remarksVM.setForeground(new java.awt.Color(51, 51, 51));
        remarksVM.setLineWrap(true);
        remarksVM.setRows(2);
        remarksVM.setWrapStyleWord(true);
        jScrollPane6.setViewportView(remarksVM);

        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Branch");

        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Classification");

        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Processed By");

        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Transaction Date");

        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("Maturity Date");

        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Expiry Date");

        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Principal");

        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Advance Interest");

        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Insurance");

        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("Service Charge");

        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("Other Charges");

        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Net Proceeds");

        branchVM.setEditable(false);
        branchVM.setBackground(new java.awt.Color(255, 255, 255));
        branchVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        branchVM.setForeground(new java.awt.Color(51, 51, 51));

        itemClassificationVM.setEditable(false);
        itemClassificationVM.setBackground(new java.awt.Color(255, 255, 255));
        itemClassificationVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        itemClassificationVM.setForeground(new java.awt.Color(51, 51, 51));

        processedByVM.setEditable(false);
        processedByVM.setBackground(new java.awt.Color(255, 255, 255));
        processedByVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        processedByVM.setForeground(new java.awt.Color(51, 51, 51));

        transactionDateVM.setEditable(false);
        transactionDateVM.setBackground(new java.awt.Color(255, 255, 255));
        transactionDateVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        transactionDateVM.setForeground(new java.awt.Color(51, 51, 51));

        maturityDateVM.setEditable(false);
        maturityDateVM.setBackground(new java.awt.Color(255, 255, 255));
        maturityDateVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        maturityDateVM.setForeground(new java.awt.Color(51, 51, 51));

        expiryDateVM.setEditable(false);
        expiryDateVM.setBackground(new java.awt.Color(255, 255, 255));
        expiryDateVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        expiryDateVM.setForeground(new java.awt.Color(51, 51, 51));

        principalVM.setEditable(false);
        principalVM.setBackground(new java.awt.Color(255, 255, 255));
        principalVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        principalVM.setForeground(new java.awt.Color(51, 51, 51));

        interestVM.setEditable(false);
        interestVM.setBackground(new java.awt.Color(255, 255, 255));
        interestVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        interestVM.setForeground(new java.awt.Color(51, 51, 51));

        insurancetVM.setEditable(false);
        insurancetVM.setBackground(new java.awt.Color(255, 255, 255));
        insurancetVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        insurancetVM.setForeground(new java.awt.Color(51, 51, 51));

        serviceChargeVM.setEditable(false);
        serviceChargeVM.setBackground(new java.awt.Color(255, 255, 255));
        serviceChargeVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        serviceChargeVM.setForeground(new java.awt.Color(51, 51, 51));

        otherChargesVM.setEditable(false);
        otherChargesVM.setBackground(new java.awt.Color(255, 255, 255));
        otherChargesVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        otherChargesVM.setForeground(new java.awt.Color(51, 51, 51));

        netProceedsVM.setEditable(false);
        netProceedsVM.setBackground(new java.awt.Color(255, 255, 255));
        netProceedsVM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        netProceedsVM.setForeground(new java.awt.Color(51, 51, 51));

        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("Item Description");

        jLabel41.setForeground(new java.awt.Color(102, 102, 102));
        jLabel41.setText("Remarks");

        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setText("Contact No.");

        contactNo.setEditable(false);
        contactNo.setBackground(new java.awt.Color(255, 255, 255));
        contactNo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        contactNo.setForeground(new java.awt.Color(51, 51, 51));

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Old Loan No.");

        oldPapNum.setEditable(false);
        oldPapNum.setBackground(new java.awt.Color(255, 255, 255));
        oldPapNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        oldPapNum.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel26)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(serviceChargeVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                                .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(transactionDateVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                                .addComponent(principalVM, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(otherChargesVM, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(interestVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                                        .addComponent(maturityDateVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                                        .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(papeletaNoVM, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(oldPapNum, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane6)
                                    .addComponent(jScrollPane5)
                                    .addComponent(jScrollPane4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientNameVM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(processedByVM)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expiryDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insurancetVM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netProceedsVM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusVM)
                            .addComponent(jLabel27)
                            .addComponent(itemClassificationVM)
                            .addComponent(jLabel29)
                            .addComponent(contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(branchVM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {expiryDateVM, insurancetVM, interestVM, maturityDateVM, netProceedsVM, otherChargesVM, principalVM, serviceChargeVM, transactionDateVM});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {branchVM, contactNo, oldPapNum, papeletaNoVM});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel28)
                    .addComponent(jLabel23))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(papeletaNoVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPapNum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel43))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemClassificationVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel27))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel30))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processedByVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maturityDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDateVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(principalVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interestVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insurancetVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceChargeVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherChargesVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netProceedsVM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel42.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(79, 119, 141));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Please confirm that all items above are TRUE and CORRECT.");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(79, 119, 141));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Are you sure you want to add this item?");

        yesButton1.setBackground(new java.awt.Color(79, 119, 141));
        yesButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        yesButton1.setForeground(new java.awt.Color(255, 255, 255));
        yesButton1.setText("Yes");
        yesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButton1ActionPerformed(evt);
            }
        });

        noButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        noButton1.setForeground(new java.awt.Color(79, 119, 141));
        noButton1.setText("No");
        noButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButton1ActionPerformed(evt);
            }
        });
        noButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noButton1KeyPressed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 102));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Merlin Pawnshop, Inc.   All Rights Reserved. © 2011");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(yesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(noButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButton1ActionPerformed
        this.allow = true;
        /* 482 */     setVisible(false);
        /* 483 */     dispose();
    }//GEN-LAST:event_yesButton1ActionPerformed

    private void noButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButton1ActionPerformed
        this.allow = false;
        /* 489 */     setVisible(false);
        /* 490 */     dispose();
    }//GEN-LAST:event_noButton1ActionPerformed

    private void noButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noButton1KeyPressed
        int key = evt.getKeyCode();
        /* 496 */     if (key == 37 || key == 9) {
            /* 497 */       this.yesButton1.requestFocusInWindow();
            /*     */     }
    }//GEN-LAST:event_noButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRenewedItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRenewedItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRenewedItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRenewedItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() { private Sangla renewedSangla;
            public void run() {
                ViewRenewedItem dialog = new ViewRenewedItem(new javax.swing.JFrame(), true, this.renewedSangla);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branchVM;
    private javax.swing.JTextArea clientAddressVM;
    private javax.swing.JTextField clientNameVM;
    private javax.swing.JTextField contactNo;
    private javax.swing.JTextField expiryDateVM;
    private javax.swing.JTextField insurancetVM;
    private javax.swing.JTextField interestVM;
    private javax.swing.JTextField itemClassificationVM;
    private javax.swing.JTextArea itemDescVM;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField maturityDateVM;
    private javax.swing.JTextField netProceedsVM;
    private javax.swing.JButton noButton1;
    private javax.swing.JTextField oldPapNum;
    private javax.swing.JTextField otherChargesVM;
    private javax.swing.JTextField papeletaNoVM;
    private javax.swing.JTextField principalVM;
    private javax.swing.JTextField processedByVM;
    private javax.swing.JTextArea remarksVM;
    private javax.swing.JTextField serviceChargeVM;
    private javax.swing.JTextField statusVM;
    private javax.swing.JTextField transactionDateVM;
    private javax.swing.JButton yesButton1;
    // End of variables declaration//GEN-END:variables
}
